from mahjong.yaku.chankan import Chankan
from mahjong.yaku.chanta import Chanta
from mahjong.yaku.chiihou import Chiihou
from mahjong.yaku.chiitoi import Chiitoi
from mahjong.yaku.chinitsu import Chinitsu
from mahjong.yaku.chinroutou import Chinroutou
from mahjong.yaku.chuurenpoutou import ChuurenPoutou
from mahjong.yaku.dabururiichi import DaburuRiichi
from mahjong.yaku.daisangen import Daisangen
from mahjong.yaku.daisuushii import Daisuushii
from mahjong.yaku.haitei import Haitei
from mahjong.yaku.honitsu import Honitsu
from mahjong.yaku.honroutou import Honroutou
from mahjong.yaku.houtei import Houtei
from mahjong.yaku.iipeikou import Iipeikou
from mahjong.yaku.ippatsu import Ippatsu
from mahjong.yaku.ittsuu import Ittsuu
from mahjong.yaku.junchan import Junchan
from mahjong.yaku.kazoeyakuman import KazoeYakuman
from mahjong.yaku.kokushimusou import KokushiMusou
from mahjong.yaku.pinfu import Pinfu
from mahjong.yaku.riichi import Riichi
from mahjong.yaku.rinshankaihou import RinshanKaihou
from mahjong.yaku.ryanpeikou import Ryanpeikou
from mahjong.yaku.ryuuiisou import Ryuuiisou
from mahjong.yaku.sanankou import Sanankou
from mahjong.yaku.sankantsu import Sankantsu
from mahjong.yaku.sanshiki import Sanshiki
from mahjong.yaku.sanshokudoukou import SanshokuDoukou
from mahjong.yaku.shousangen import Shousangen
from mahjong.yaku.shousuushii import Shousuushii
from mahjong.yaku.suuankou import Suuankou
from mahjong.yaku.suukantsu import Suukantsu
from mahjong.yaku.tanyao import Tanyao
from mahjong.yaku.tenhou import Tenhou
from mahjong.yaku.toitoi import Toitoi
from mahjong.yaku.tsumo import Tsumo
from mahjong.yaku.tsuuiisou import Tsuuiisou
from mahjong.yaku.yakuhai import Yakuhai

from mahjong.yaku.utils import YAKU_CHECKING_ORDER
